version: '3.9'

networks:
  restcountries_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.5.0/24

services:
  mysql:
    image: mysql
    container_name: main_database
    restart: unles-stop
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: restcountries.db
    ports:
      - "3306:3306"
    networks:
      - restcountries_network

  redis:
    image: redis:7.4-alpine3.21
    container_name: session_store
    restart: unles-stop
    ports:
      - "6379:6379"
    networks:
      - restcountries_network

  node_app:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    container_name: node_app
    restart: unles-stop
    working_dir: /app
    ports:
      - "3001:3001"
    networks:
      - restcountries_network
    depends_on:
      - mysql
