# Use a smaller base image
FROM node:23-alpine3.20

# Set working directory
WORKDIR /app

# Install dependencies only when needed
COPY package*.json ./

# Install dependencies (only production dependencies for smaller size)
RUN npm ci --omit=dev

# Copy only necessary files
COPY . .

# Expose the port
EXPOSE 3001

# Use a non-root user (optional but recommended for security)
RUN addgroup app && adduser -S -G app app
USER app

# Start the application
CMD ["npm", "run", "start"]
